user:
  name: "Harvey"
  id: "B8ZEuzqbpIH47rwo"

phenobottle:
  version: "0.2"
  id: "WUCLGgcXmPBfGxdo"
  treatment: "control"

broker:
  address: "mqtt.phenobottle.xyz"
  port: 8883
  certs: "certs/isrgrootx1.cer"

serial:
  port: "/dev/tty.usbmodem81500001"
